class MockData {
  static final List<String> names = [
    'Aeiyan',
    'Aiden',
    'Ali',
    'Andrew',
    'Armaan',
    'Arvind',
    'Athina',
    'Ben',
    'Benjamin',
    'Brandon',
    'Brendan',
    'Brett',
    'Chetram',
    'Cole',
    'Danindu',
    'Elliot',
    'Emily K.',
    'Emily R.',
    'Eric',
    'Faisal',
    'Gali',
    'Gavin',
    'Graham',
    'Gurveen',
    'Humzah',
    'Jacob',
    'Jake',
    'Jason',
    'Jeffery',
    'Jennifer',
    'Jeremy',
    'Jerrell',
    'Jessica',
    'Joffre',
    'Joudat',
    'Julia',
    'Justin',
    'Kabilaash',
    'Kailey',
    'Kathryn',
    'Liang',
    'Lucas',
    'Madhurbain',
    'Manav',
    'Mandy',
    'Markus',
    'Mehtab',
    'Mrudini',
    'Muhammad',
    'Nathan',
    'Nelith',
    'Nicholas',
    'Nitin',
    'Or',
    'Patrick',
    'Peter',
    'Priscilla',
    'Rawhi',
    'Sarah',
    'Sean',
    'Sukhman',
    'Syed',
    'Talha',
    'Thanush',
    'Theo',
    'Trisha',
    'Uzair',
    'Vlad',
    'William B.',
    'William S.',
    'Yash',
    'Zach',
  ];

  static final List<String> lessons = List.generate(10, (index) => 'Lesson ${index + 1}');
}